### ISSUE TITLE
sets background correctly on neovim-qt but not in alacritty/kitty

### ISSUE THREAD

**Issue by jam1015** [pappasam/papercolor-theme-slim#3]
In both alacritty/kitty I don't have any colors set in their respective configs; just running the default colors.  I install this colorscheme using Lazy.nvim and reduce my vimrc to just having.
 

```
vim.cmd([[
set background=light
colorscheme PaperColorSlim
]])
```

The colorscheme background is properly loaded neovim-qt but in alacritty/kitty the background of the terminal is used, even without the autocommand you include in the readme

**Comment by pappasam** [comment]
Hmm, I don't have this issue (I use Alacritty).

Which operating system are you using? Maybe this issue is relevant? https://github.com/alacritty/alacritty/issues/4070
